---
# tasks file for mysql_db
    - name: Install and Configure MYSQL Database
      apt: name="{{ item }}" state=present
      with_items:
        - mysql-server
        - mysql-client

    - name: Start MySQL Database Service
      service: name=mysql state=started enabled=yes

#    - name: Copy my.cnf to host
#      copy: src=my.cnf dest=/root/.my.cnf

    - name: Create database user with name 'db_user' and password 'Passw0rd' with all database privileges
      mysql_user:
        name: '{{ db_user }}'
        password: '{{ db_user_password }}'
        priv: '*.*:ALL,GRANT'
        state: present
        host_all: yes

    - name: Create a new database with name "employee_db"
      mysql_db:
        name: '{{ db_name }}'
        state: present